### ISSUE TITLE
Help getting started with this for noob

### ISSUE THREAD

**Issue by johncblacker** [VimalShekar/PowerShell#1]
I'm a powershell neophyte, so how do I get started with this.  If I create and then execute the script, I get no output.  Does this have to be installed somehow or am I missing something?

**Comment by mrmattipants** [comment]
> I'm a powershell neophyte, so how do I get started with this. If I create and then execute the script, I get no output. Does this have to be installed somehow or am I missing something?

The PowerShell Script consists of a couple Functions. Therefore, you need to Call the Primary Function (Get-CrenManCreds), in order to Run it.

If you are trying to Run the "GetCredManCreds.ps1" Script, directly from the PowerShell ISE Editor, then simply add the Name of the Function to the Bottom of the Script. Then Save and Run.
**Get-CredManCreds**

However, if you want to Call the Function from a New PowerShell Window, then you can use the CD Command to Set the Current Directory to the Folder, that contains the GetCredManCreds.ps1 File (For example, if the file is Stored in the "C:\temp" Folder, use "CD C:\temp" to Change to that Directory). 
Then Reference the .ps1 File using the following Command (note the dot space dot before the backslash) and Press your "Enter" Key.
**. .\GetCredManCreds.ps1**
Finally, Call the "Get-CredManCreds" Function on the next line, by Typing the Name of the Function and Pressing "Enter".
**Get-CredManCreds**

I hope this helps.

**Comment by VimalShekar** [comment]
So sorry I didn't get to this sooner @johncblacker and Thanks for answering that Question @mrmattipants 
Marking this as closed
